rango/urls.py
from django.conf.urls import url
from rango import views

app_name = 'rango'

urlpatterns = [
url(r'^$', views.index, name='index'),
url(r'^about/$',views.about,name = 'about'),
url(r'^category/(?P<category_name_slug>[\w\-]+)/$',views.show_category,name='show_category'),
url(r"^add_category/$",views.add_category,name = "add_category"),
url(r'^category/(?P<category_name_slug>[\w\-]+)/add_page/$', views.add_page, name='add_page'),
url(r'^register/$',views.register,name = "register"),
url(r'^login/$',views.user_login,name="login"),
url(r'^restricted/$',views.restricted,name = "restricted"),
url(r'^logout/$',views.user_logout,name = "logout"),
url(r'^goto/$',views.track_url,name = "goto"),
url(r'^register_profile/$', views.register_profile, name='register_profile'),
]

tango_with_django_project/urls.py
from django.contrib import admin
from django.urls import path
from rango.views import index
from django.conf.urls import url,include
from django.conf import settings
from django.conf.urls.static import static
from registration.backends.simple.urls import RegistrationView


class MyRegistrationView(RegistrationView):
    def get_success_url(self, user):
        return '/rango/'

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^$',index),
    url(r'^rango/', include('rango.urls')),
    url(r'^accounts/register/$',MyRegistrationView.as_view(),name='registration_register'),
    url(r'^accounts/', include('registration.backends.simple.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

rango/models.py
from django.db import models
import uuid
from django.template.defaultfilters import slugify
from django.contrib.auth.models import User

class Category(models.Model):
    name = models.CharField(max_length=125, unique=True)
    views = models.IntegerField(default=0)
    likes = models.IntegerField(default=0)
    slug = models.SlugField(blank= True,max_length=31,help_text="Category of Website")

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super(Category,self).save(*args,**kwargs)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = "Categories"


class Page(models.Model):
    category = models.ForeignKey(Category,on_delete = models.DO_NOTHING)
    title = models.CharField(max_length=125)
    url = models.URLField()
    views = models.IntegerField(default=0)
    likes = models.IntegerField(default=0)

    def __str__(self):
        return self.title


class UserProfile(models.Model):
    user = models.OneToOneField(User,on_delete= models.DO_NOTHING)
    website = models.URLField(blank=True)
    picture = models.ImageField(upload_to="profile_images",blank= True)

    def __str__(self):
        return self.user.username



# Create your models here.

rango/forms.py
from django import forms
from rango.models import Page,Category,UserProfile
from django.contrib.auth.models import User

class CategoryForm(forms.ModelForm):
    name = forms.CharField(max_length=128,help_text="Enter the category name")
    views = forms.IntegerField(widget = forms.HiddenInput(),initial = 0)
    likes = forms.IntegerField(widget = forms.HiddenInput(),initial = 0)
    slug = forms.CharField(widget= forms.HiddenInput(),required=False)

    class Meta:
        model = Category
        fields = ('name',)  #inline class to provide an association between model form and an already existing model


class PageForm(forms.ModelForm):
    title = forms.CharField(max_length=128,help_text="Enter the title")
    url = forms.URLField(max_length = 200,help_text="Enter the URL of the page")
    views = forms.IntegerField(widget = forms.HiddenInput(),initial = 0)

    def clean(self):
        cleaned_data = self.cleaned_data  # ModelForm has the attribute cleaned_data which is being manipulated : Dict
        url = cleaned_data.get('url')    # .get() of a dict to get values

        if url and not url.startswith('http://'):
            url = "http://" + url
            cleaned_data['url'] = url

        return cleaned_data   
        # basically getting the cleaned input from the site and furthur cleaning it to change it to the proper format

    class Meta:
        exclude = ('category',)
        model = Page
        #to specify the fields which need to be included use the tuple(fields(...))


class UserForm(forms.ModelForm):
    password = forms.CharField(widget = forms.PasswordInput())

    class Meta:
        model = User
        fields = ('username','email','password',)

class UserProfileForm(forms.ModelForm):
        class Meta:
            model = UserProfile
            fields = ('website','picture',)

rango/views.py
from django.shortcuts import render
from django.http import HttpRequest,HttpResponse,HttpResponseRedirect
from django.http.response import Http404
from django.shortcuts import get_object_or_404
from django.shortcuts import render
from django.template import loader,Template,Context
from rango.models import Category,Page
from rango.forms import CategoryForm,PageForm,UserForm,UserProfileForm
from django.contrib.auth import authenticate,login,logout
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from datetime import datetime
from django.shortcuts import redirect

def index(request):
    request.session.set_test_cookie()
    context_list = Category.objects.order_by('-likes')[:5]
    context_dict = { 'categories' : context_list}
    visitor_cookie_handler(request)
    context_dict['visits'] = request.session['visits']
    return render(request,'rango/index.html',context= context_dict)
   

def about(request):
    if request.session.test_cookie_worked():
        print("Test Cookie Worked!")
        request.session.delete_test_cookie()
    return render(request,'rango/about.html',context = None)

def show_category(request, category_name_slug):
    context_dict = {}

    try:
        category = Category.objects.get(slug = category_name_slug)
        #pages = Page.objects.filter(category = category)
        pages = Page.objects.filter(category=category).order_by('-views')
        context_dict['pages'] = pages
        context_dict['category'] = category

    except Category.DoesNotExist:
            context_dict['category'] = None
            context_dict['pages'] = None
    
    context_dict['query'] = category.name
    result_list = []
    if request.method == 'POST':
        query = request.POST['query'].strip()
        if query:
            context_dict['query'] = query
            context_dict['result_list'] = result_list
    return render(request,'rango/category.html',context_dict)


def add_category(request):

    form = CategoryForm()

    if request.method == 'POST' :   # POST : user submits data through the form 
        form = CategoryForm(request.POST)

        if form.is_valid():
            cat = form.save(commit=True)
            return index(request)  #direct user back to index page
        
        else:
            print(form.errors)  #print errors in form inputs

    context_dict = {'form' : form}

    return render(request,'rango/add_category.html',context_dict)

def add_page(request,category_name_slug):

    try:
        category = Category.objects.get(slug = category_name_slug)
    except Category.DoesNotExist :
        category = None

    form = PageForm()

    if request.method == "POST":
        form = PageForm(request.POST)

        if form.is_valid():
            if category:
                page = form.save(commit = False)
                page.category = category
                page.views = 0
                page.save()
                return show_category(request,category_name_slug)  # redirect user to the page list for that category

        else:
            print(form.errors)

    context_dict = {'form' : form , 'category' : category}
    return render(request,'rango/add_page.html',context_dict)


def register(request):
    registered = False # to check whether the user is already registered

    if request.method == "POST":
        user_form = UserForm(data = request.POST)
        profile_form = UserProfileForm(data = request.POST)

        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()

            profile = profile_form.save(commit = False)
            profile.user = user

            if  'picture' in request.FILES:
                profile.picture = request.FILES['picture']

            profile.save()
            registered = True
    
        else:
            print(user_form.errors,profile_form.errors)

    else:
        user_form = UserForm()
        profile_form = UserProfileForm()

    context_dict = {'user_form' : user_form, 'profile_form' : profile_form, 'registered' : registered}

    return render(request,'rango/register.html',context_dict)


def user_login(request):

    if request.method == "POST" : 
        username = request.POST.get('username')
        password = request.POST.get('password')  #info already obtained from the login form
        user = authenticate( username = username,password = password)

        if user:
            if user.is_active:
                login(request,user)
                return HttpResponseRedirect(reverse('rango:index'))
            else:
                return HttpResponse("Your Rango Account has been disabled")
        else:
            print("Invalid Login Details: {0},{1}".format(username,password))
            return HttpResponse("Invalid Login Details Entered")

    else:
        context_dict = {}
        return render(request,'rango/login.html',context_dict)

@login_required
def restricted(request):
    return HttpResponse("Since you are logged in, you can see this text!")

@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('rango:index'))

def get_server_side_cookie(request,cookie,default_val = None): #helper method
    val = request.session.get(cookie)
    if not val:
        val = default_val
    return val

def visitor_cookie_handler(request):
    visits = int(get_server_side_cookie(request,'visits',1))

    last_visit_cookie = get_server_side_cookie(request,'last_visit', str(datetime.now()))
    last_visit_time = datetime.strptime(last_visit_cookie[:-7],'%Y-%m-%d %H:%M:%S')

    if (datetime.now() - last_visit_time).days > 1:
        visits+=1
        request.session['last_visit'] = str(datetime.now())
    
    else:
        visits = 1
        request.session['last_visit'] = last_visit_cookie

    request.session['visits'] = visits
     #instead of storing the cookies in the request and on the client's machine, we are storing the cookie in the server side
     # in request.session dictionary 

def track_url(request):
    page_id = None
    url = "/rango/"

    if request.method == "GET":
        if 'page_id' in request.GET:
            page_id = request.GET['page_id']

            try:
                page = Page.objects.get(id = page_id)
                page.views+=1
                page.save()
                url = page.url
            except:
                pass
    return redirect(url)

def search(request):
    result_list = []
    if request.method == 'POST':
        query = request.POST['query'].strip()
        if query:
            # Run our Bing function to get the results list!
            result_list = run_query(query)
    return render(request, 'rango/category.html', {'result_list': result_list})


@login_required
def register_profile(request):

    form = UserProfileForm()

    if request.method == "POST":
        form = UserProfileForm(request.POST,request.files)
        if form.is_valid():
            user_profile = form.save(commit=False)
            user_profile.user = request.user
            user_profile.save()
            return redirect('index')
        else:
            form.errors
    
    context_dict = {'form' : form}
    return render(request,'rango/profile_registration.html',context_dict)

templates/rango/about.html
{% extends 'rango/base.html' %}
<!DOCTYPE html>
{% load static %}


{% block title_block %}
<head>
    About
</head>
{% endblock %}
{% block body_block %}
<div>
    <body>
        <p>
            Coded By Kaustubh V. in March 2020
        </p>

        <img src ="{% static "images/about.png" %}" alt = "About"/>
       
        <button class="btn btn-primary"
        onClick="alert('You clicked the button using JavaScript.');">
        Click Me - I run JavaScript
        </button>

        <button class="btn btn-primary" id="about-btn">
            Click Me - I'm JavaScript on Speed</button>
            <p>This is a example</p>
            <p>This is another example</p>
    </body>
</div>
{% endblock %}

templates/rango/add_category.html
{% extends "rango/base.html" %}
<!--<!DOCTYPE html>

<head>
    <title>
        Rango
    </title>
</head>

<body>
    <h1> Add a Category </h1>
    <div>
        <form id = "category_form" method = "post" action = "/rango/add_category">
        {% csrf_token %}
        {% for hidden in form.hidden_fields %}
        {{ hidden }}
        {% endfor %}

        {% for field in form.visible_fields %}
        {{ field.errors }}
        {{field.help_text}}
        {{ field }}
        {% endfor %}
        <input type = "submit" name = "submit" value = "Create Category"/>
        </form>
    </div>
</body>
-->

{% load bootstrap_toolkit %}
{% block title %}Add Category{% endblock %}
{% block body_block %}
<form id="category_form" method="post"
action="{% url 'rango:add_category' %}"\>
<h2 class="form-signin-heading"\>Add a Category</a></h2>
{% csrf_token %}
{{ form|as_bootstrap }}
<br/>
<button class="btn btn-primary" type="submit" name="submit"\>Create Category</button>
</form>
{% endblock %}

templates/rango/add_page.html
{% extends "rango/base.html" %}
{% load bootstrap_toolkit %}
{% block title %}Add Page{% endblock %}
{% block body_block %}
{% if category %}
<form role="form" id="page_form" method="post"
action="/rango/category/{{category.slug}}/add_page/">
<h2 class="form-signin-heading"> Add a Page to
<a href="/rango/category/{{category.slug}}/">
{{ category.name }}</a></h2>
{% csrf_token %}
{% for hidden in form.hidden_fields %}
{{ hidden }}
{% endfor %}
{% for field in form.visible_fields %}
{{ field.errors }}
{{ field.help_text }}<br/>
{{ field }}<br/>
{% endfor %}
<br/>
<button class="btn btn-primary"
type="submit" name="submit">
Add Page
</button>
</form>
{% else %}
<p>This is category does not exist.</p>
{% endif %}
{% endblock %}

templates/rango/base.html
{% extends 'rango/base_bootstrap.html' %}
<!DOCTYPE html>
{% load rango_template_tags %}
{% load static %}

<html>
    <head lang="en">
        <meta charset="UTF-8"/>
        <title>
            Rango - {% block title_block %}
            How to Tango with Django !
            {% endblock %}
        </title>
    </head>
    <body>
        <div>
        {% block body_block %}
        This is the block's default content.
        {% endblock %}
        </div>
        <hr/>
        <div>
            <ul>
                <li>
                    <a href="{% url 'rango:add_category' %}">Add New Category</a>
                </li>
                <li>
                    <a href = "{% url 'rango:about' %}">About</a>
                </li>
                <li>
                    <a href = "{% url 'rango:index' %}">Index</a>
                </li>
                <li>
                    <a href="{% url 'auth_login' %}">Login</a>
                </li>
                <li>
                    <a href = "{% url 'registration_register' %}">Sign Up!</a>
                </li>
                <li>
                    <a href="{% url 'auth_logout' %}?next=/rango/">Logout</a>
                </li>
            </ul>
        </div>

        <div>
            {% block sidebar_block %}
            {% get_category_list category %}
            {% endblock %}
            </div>

    </body>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.0.0/jquery.min.js"></script>
<script src="{% static "js/rango-jquery.js" %}"></script>
</html>

templates/rango/base_bootstrap.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
{% load rango_template_tags %}
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="{% static 'images/favicon.ico' %}">

      <title>Rango - {% block title %}How to Tango with Django!{% endblock %}</title>
      <!-- Bootstrap core CSS -->
    <link href="http://v4-alpha.getbootstrap.com/dist/css/bootstrap.min.css" rel="stylesheet">

    <link href="http://v4-alpha.getbootstrap.com/examples/dashboard/dashboard.css" rel="stylesheet">

  </head>

  <body>

    <nav class="navbar navbar-toggleable-md navbar-inverse fixed-top bg-inverse">
      <button class="navbar-toggler navbar-toggler-right hidden-lg-up" type="button" data-toggle="collapse" data-target="#navbar" aria-controls="navbar" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <a class="navbar-brand" href="{% url 'rango:index' %}">Rango</a>

      <div class="collapse navbar-collapse" id="navbar">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'rango:index' %}">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'rango:about' %}">About</a>
          </li>
        {% if user.is_authenticated %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'rango:add_category' %}">Add a New Category</a>
            </li>
            
            <li class="nav-item">
              <a class="nav-link" href="{% url 'auth_logout' %}?next=/rango/">Logout</a>
            </li>
        {% else %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'registration_register' %}">Register Here</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'auth_login' %}">Login</a>
            </li>
        {% endif %}
        </ul>
      </div>
    </nav>

    
        <div class="col-sm-9 offset-sm-3 col-md-10 offset-md-2 main">
         {% block body_block %}{% endblock %}


        </div>
      </div>
    </div>

     <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.0.0/jquery.min.js" integrity="sha384-THPy051/pYDQGanwU6poAc/hOdQxjnOEXzbT+OuUAFqNqFjL+4IGLBgCJC3ZOShY" crossorigin="anonymous"></script>
 <!--
    <script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery.min.js"><\/script>')</script>
 -->
   <script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.2.0/js/tether.min.js" integrity="sha384-Plbmg8JY28KFelvJVai01l8WyZzrYWG825m+cZ0eDDS1f7d/js6ikvy1+X+guPIB" crossorigin="anonymous"></script>
    <script src="http://v4-alpha.getbootstrap.com/dist/js/bootstrap.min.js"></script>
    <!-- Just to make our placeholder images work. Don't actually copy the next line! -->
    <!--
    <script src="http://v4-alpha.getbootstrap.com/assets/js/vendor/holder.min.js"></script>
    -->

    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="http://v4-alpha.getbootstrap.com/assets/js/ie10-viewport-bug-workaround.js"></script>
    <script src="{% static "js/rango-ajax.js" %}"></script>
    <script src="{% static "js/rango-jquery.js" %}"></script>
  </body>
</html>

templates/rango/category.html
{% extends "rango/base.html" %}
{% load static %}
<!DOCTYPE html>
{% load static %}

{% block title_block %}
    {{category.name}}
{% endblock %}

{% block body_block %}
{% if category %}
<h1>{{category.name}}</h1>
{% if pages %}
<ul>
{% for page in pages %}
<li><a href = "{{page.url}}">{{page.title}}</a></li>
{% endfor %}
</ul>
{% else %}
<strong>No Pages in this Category</strong>
{% endif %}
<a href="{% url 'rango:add_page' category.slug %}">Add a new Page</a>
{% else %}
<h1>The Given category does not exist.</h1>
{% endif %}

<div>
    <form class="form-inline" id="user_form" method="post" action="{% url 'rango:show_category' category.slug %}">
        {% csrf_token %}
       <div class="form-group">
           <input class="form-control" type="text" size="50" name="query" value="{{query}}" id="query"/>
       </div>
       <button class="btn btn-primary" type="submit" name = "submit" value="Search">Search</button>
    </form>
</div>
</body>

<div>
   {% if result_list %}
   <h3>Results</h3>
   <!-- Display search results in an ordered list -->
   <div class="list-group">
   {% for result in result_list %}
   <div class="list-group-item">
   <h4 class="list-group-item-heading">
   <a href="{{ result.link }}">{{ result.title }}</a>
   </h4>
   <p class="list-group-item-text">{{ result.summary }}</p>
   </div>
   {% endfor %}
   </div>
   {% endif %}
   </div>

{% endblock %}

<!--
<!DOCTYPE html>
 <html>
 <head>
 <title>Rango</title>
 </head>
 <body>
 <div>
 {% if category %}
 <h1>{{ category.name }}</h1>
 {% if pages %}
 <ul>
 {% for page in pages %}
 <li>
    <a href="{% url 'rango:goto' %}?page_id={{page.id}}">{{ page.title }}</a>
    {% if page.views > 1 %}
    ({{ page.views }} views)
    {% elif page.views == 1 %}
    ({{ page.views }} view)
    {% endif %}
    </li>
 {% endfor %}
 </ul>
 {% else %}
 <strong>No pages currently in category.</strong>
 {% endif %}
 {% else %}
 The specified category does not exist!
 {% endif %}
 </div>
 <a href = "/rango/category/{{category.slug}}/add_page/">Add a new Page to this Category</a>

 
 </html>
-->

templates/rango/cats.html
{% for c in cats %}
{% if c == act_cat %}
<li>
<strong>
<a href="{% url 'rango:show_category' c.slug %}">{{ c.name }}</a>
</strong>
</li>
{% else %}
<li>
<a href="{% url 'rango:show_category' c.slug %}">{{ c.name }}</a>
</li>
{% endif %}
{% endfor %}

templates/rango/index.html
{% extends 'rango/base.html' %}
{% load static %}
{% block title_block %}
Index
{% endblock %}
{% block body_block %}
<div class="jumbotron">
<h1 class="display-3">Rango says...</h1>
{% if user.is_authenticated %}
<h1>hey there {{ user.username }}!</h1>
{% else %}
<h1>hey there partner! </h1>
{% endif %}
</div>
<div class="row marketing">
<div class="col-lg-6">
<h4>Most Liked Categories</h4>
<p>
{% if categories %}
<ul>
{% for category in categories %}
<li><a href="{% url 'rango:show_category' category.slug %}">
{{ category.name }}</a></li>
{% endfor %}
</ul>
{% else %}
<strong>There are no categories present.</strong>
{% endif %}
</p>
</div>
<div class="col-lg-6">

    <h4>Most Viewed Pages</h4>
<p>
{% if pages %}
<ul>
{% for page in pages %}
<li><a href="{{ page.url }}">{{ page.title }}</a></li>
{% endfor %}
</ul>
{% else %}
<strong>There are no categories present.</strong>
{% endif %}
</p>
</div>
</div>
<img src="{% static "images/rango.jpg" %}" alt="Picture of Rango" />
{% endblock %}

templates/rango/login.html
{% extends 'rango/base.html' %}

<!DOCTYPE html>

{% block title_block %}
    Login
{% endblock %}

{% block body_block %}
<link href="http://v4-alpha.getbootstrap.com/examples/signin/signin.css"
rel="stylesheet">
<div class="jumbotron">
<h1 class="display-3">Login</h1>
</div>
<form class="form-signin" role="form" method="post" action=".">
{% csrf_token %}
<h2 class="form-signin-heading">Please sign in</h2>
<label for="inputUsername" class="sr-only">Username</label>
<input type="text" name="username" id="id_username" class="form-control"placeholder="Username" required autofocus/>

<label for="inputPassword" class="sr-only">Password</label>
<input type="password" name="password" id="id_password" class="form-control" placeholder="Password" required/>
<button class="btn btn-lg btn-primary btn-block" type="submit"value="Submit">Sign in</button>
</form>
{% endblock %}

templates/rango/profile_registration.html
{% extends "rango/base.html" %}
{% block title_block %}
Registration - Step 2
{% endblock %}
{% block body_block %}
<h1>Registration - Step 2</h1>
<form method="post" action="." enctype="multipart/form-data">
{% csrf_token %}
{{ form.as_p }}
<input type="submit" value="Submit" />
</form>
{% endblock %}

templates/rango/register.html
{% extends 'rango/base.html' %}
<!DOCTYPE html>
{% load static %}


{% block title_block %}
    Register!
{% endblock %}

{% block body_block %}
<h1> About Page </h1>
{% if registered %}
Rango Says : <strong> Thank you for registering!</strong>
<a href="{% url 'rango:index' %}">Return to HomePage</a><br/>

{% else %}
Rango Says : <strong>Register Here!</strong>
<form id = "user_form" method="post" action = "{% url 'rango:register' %}" enctype="multipart/form-data">

{% csrf_token %}

{{user_form.as_p}}
{{profile_form.as_p}}

<input type = "submit" name="submit" value = "register"/>
</form>
{% endif %}
{% endblock %}

templates/rango/search.html
 {% extends 'rango/base.html' %}
 {% load static %}

 {% block title %} Search {% endblock %}

 {% block body_block %}
 <div>
 <h1>Search with Rango</h1>
 <br/>
 <form class="form-inline" id="user_form"
 method="post" action="{% url 'search' %}">
 {% csrf_token %}
 <div class="form-group">
 <input class="form-control" type="text" size="50" name="query" value="" id="query" />
 </div>
 <button class="btn btn-primary" type="submit" name="submit" value="Search">Search</button>
 </form>

 <div>
 {% if result_list %}
 <h3>Results</h3>
 <!-- Display search results in an ordered list -->
 <div class="list-group">
 {% for result in result_list %}
 <div class="list-group-item">
 <h4 class="list-group-item-heading">
 <a href="{{ result.link }}">{{ result.title }}</a>
 </h4>
 <p class="list-group-item-text">{{ result.summary }}</p>
 </div>
 {% endfor %}
 </div>
 {% endif %}
 </div>
 </div>
 {% endblock %}